### ISSUE TITLE
Workflow example?

### ISSUE THREAD

**Issue by vsoch** [Zymo-Research/VirSieve#1]
Hi! Is there any example that puts these containers into a workflow and demonstrates running, possibly with open source data? I saw nextflow mentioned in the README but don’t see any files for it. We are looking to showcase a new Lubernetes operator and looking for complex workflows. Thanks!

**Comment by michael-weinstein** [comment]
I haven't done one yet, but would be happy to see how I can help.

**Comment by vsoch** [comment]
Awesome! Is there any documentation anywhere about these git sub modules (that I suspect build into containers?)

**Comment by michael-weinstein** [comment]
I don't think I got documentation turned out, but I can put some together.  If I recall, it was essentially automated from the point of mounting a folder of fastq files into the container.

**Comment by michael-weinstein** [comment]
Finally getting back to this and trying to get it across the finish line.  Made some significant updates to it.
